### ISSUE TITLE
[Bug] Strange memory usage

### ISSUE THREAD

**Issue by MrAlucardDante** [MauriceNino/dashdot#119]
### Description of the bug

Memory usage in Dashdot : 11GB
Memory usage in free: 10GB
Memory usage in top: 73MB (but actually around 10GB)
Memory usage in htop: 3.5GB

Free and top take into account the buffer and cache, and I guess Dashdot uses similar tools.

htop shows the actual memory being used (since buffered and cached memory are reserved by the OS and not really used, from what I understand at least).

I feel like it would be more useful to display the actual memory being used, like htop does (RES and not VIRT/SHR).

Here is an interesting article I've found, hope it helps in some way
https://peteris.rocks/blog/htop/
![WindowsTerminal_O3hSYRUyrs](https://user-images.githubusercontent.com/20476382/174076074-304bc371-e27e-4dc7-aa9e-b5527162032c.png)
![WindowsTerminal_YoEp9nOBCH](https://user-images.githubusercontent.com/20476382/174076084-29c5be01-0b30-428c-b938-1c0964e71511.png)
![WindowsTerminal_HQqD2Cwvqb](https://user-images.githubusercontent.com/20476382/174076086-79713053-7da3-4816-967b-05ff7b70aee0.png)

**Comment by MauriceNino** [comment]
Thanks for the issue, but unfortunately I can't really reproduce it. I don't know what htop shows, but the system monitor in Linux shows the exact same result as dashdot.

Then the only thing "wrong" is, that I am using the 1024 base calculations, while writing "GB" instead of "GiB". This is not "really" wrong per-se, because "GB" (and "MB", "KB") gets used interchangeably, but it is technically wrong and confusion may arise. So I will switch to the unambiguous 1024 base measurements of "GiB", "MiB" and "KiB" to avoid any further confusion.
