### ISSUE TITLE
[Bug] Current measurements are missing since 3.9.x

### ISSUE THREAD

**Issue by MrAlucardDante** [MauriceNino/dashdot#156]
### Description of the bug

Since the release of 3.9.x, the current measurements (networks speed, CPU/RAM/Storage percent) are hidden.
Reverting to 3.8.2 bring them back
![firefox_W9c2ZcTUiW](https://user-images.githubusercontent.com/20476382/176163501-80a18ac6-bfdd-4759-bda8-ef1a967f563a.png)

### How to reproduce

1. Update to 3.9.0 or 3.9.1
2. Open the dashboard
3. Downgrade to 3.8.2
4. Open the dashboard

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Where is your instance running?

Linux Server

**Comment by MauriceNino** [comment]
Hey, thanks for reporting! This is intentional - I have decided, that it takes away from the generally clean look of Dashdot.

If you want to bring them back, there is a new flag `DASHDOT_ALWAYS_SHOW_PERCENTAGES "true"`. I forgot to add it to the docs, but I have fixed that now and the docs will be live in about 30 mins. Thank you!

**Comment by MauriceNino** [comment]
Here is the documentation, in case someone needs it: https://getdashdot.com/docs/config#dashdot_always_show_percentages
