### ISSUE TITLE
[Feature] Disable speedtesting

### ISSUE THREAD

**Issue by Sloth-on-meth** [MauriceNino/dashdot#288]
### Description of the feature

i want to be able to disable speedtesting since my internet is kinda slow and when it does run it takes all of my speed. i just want to disable it entirely

**Comment by AuthorShin** [comment]
Hello
You can achieve this by setting the environment variable [DASHDOT_SPEED_TEST_INTERVAL](https://getdashdot.com/docs/config/widget-options/network#dashdot_speed_test_interval) to a higher number than default which is 240 (every 4 hours).

**Comment by Sloth-on-meth** [comment]
I want to disable it entirely, though

**Comment by AuthorShin** [comment]
Add a big number like 240000000000 and it will never test again.
I understand you want an option for turning it off but till then it's your best bet.

**Comment by MauriceNino** [comment]
Hey there, thanks for the issue and also thanks @AuthorShin for providing information! :)

You can also hide the results on the frontend by using [`DASHDOT_NETWORK_LABEL_LIST`](https://getdashdot.com/docs/config#dashdot_network_label_list) and excluding the variables `speed_up` and `speed_down`.

Unfortunately, I still kind of need one run, so that I have a base value for the network graphs. Otherwise, they would jump around a lot. That's why there is currently no way of disabling it and why I do not plan of adding a way.
