### ISSUE TITLE
[Bug] Configuration does not take effect 

### ISSUE THREAD

**Issue by HyWell** [MauriceNino/dashdot#596]
### Description of the bug

Synology DS1821+
Use `docker container run -it   --env DASHDOT_ENABLE_CPU_TEMPS="true"   -p 7512:3001   --privileged   -v /:/mnt/host:ro   mauricenino/dashdot`
DASHDOT_ENABLE_CPU_TEMPS not work
<img width="889" alt="image" src="https://user-images.githubusercontent.com/21263451/220157283-79b55835-10fc-41da-8389-d00f6a9cd3f1.png">
doesn't show the right storage data
<img width="692" alt="image" src="https://user-images.githubusercontent.com/21263451/220157420-0b06e130-30c7-41aa-928b-be1ff84f331d.png">

**Comment by MauriceNino** [comment]
Hello there!
Unfortunately, Synology is not a supported OS. I would recommend you asking in the Synology Discord server for help - maybe someone knows more about this topic.
I have no device running Synology, so I have no idea on how to make this work.
As far as I know, running in Synology messes with the mounts, so that means that the storage, the network, the cpu temperature and basically everything that is read from the file system will probably not work.

If you do however find a way to make it work reliably, I would really appreciate a contribution to the docs, or a comment on this issue.
