### ISSUE TITLE
[Feature] Running network speed test at the specified time

### ISSUE THREAD

**Issue by smtrfnv** [MauriceNino/dashdot#889]
### Description of the feature

Currently it is possible to control when network speed test is executed only using `DASHDOT_SPEED_TEST_INTERVAL` parameter. Unfortunately there is no easy way to set speed test schedule that it is executed only during selected hours.

**Comment by MauriceNino** [comment]
Hi there, sorry for the late reply. I could potentially implement some kind of cron syntax for the interval variables, so that it only updates then. Would that work for you?

**Comment by smtrfnv** [comment]
Yes, definitely!

**Comment by PilaScat** [comment]
How can I disable the speedtest feature? I don't need that

**Comment by MauriceNino** [comment]
@PilaScat You can configure [`DASHDOT_SPEED_TEST_FROM_PATH`](https://getdashdot.com/docs/configuration/network#dashdot_speed_test_from_path), so that it works without executing a speedtest. Or otherwise, remove the network widget from the page with [`DASHDOT_WIDGET_LIST`](https://getdashdot.com/docs/configuration/basic#dashdot_widget_list)

**Comment by PilaScat** [comment]
But I wanted to keep the graph, I only wanted to disable the speedtest and set a fixed bandwidth

**Comment by MauriceNino** [comment]
@PilaScat Then setup [DASHDOT_SPEED_TEST_FROM_PATH](https://getdashdot.com/docs/configuration/network#dashdot_speed_test_from_path), as I said.

**Comment by PilaScat** [comment]
Perfect I understood and did it
