### ISSUE TITLE
[Bug] Using a high value for DASHDOT_SPEED_TEST_INTERVAL causes issues

### ISSUE THREAD

**Issue by lopazopy** [MauriceNino/dashdot#927]
### Description of the bug

I wanted to run the speed test 1 time a month and entered a value of 43800. When I made this change, CPU and RAM went to 100% with network downloading at full speed and my system would freeze up. Finally, after removing the environment variable, things went back to normal.

I know how to "disable" the speed test by using a local file now.

### How to reproduce

Running dash using docker compose on Linux Mint 21.1

environment:
  DASHDOT_SPEED_TEST_INTERVAL: '43800'

### What browsers are you seeing the problem on?

Firefox

### Where is your instance running?

Desktop PC (Linux)

**Comment by MauriceNino** [comment]
Okay, I have now investigated this and came to the conclusion that this happens because the number is actually too large. The maximum number javascript can handle for `setInterval` is `2.147.483.647` according to [this](https://stackoverflow.com/a/12633485/9150652). The number you passed resolves to `2.628.000.000`.

Unfortunately, there is not much I can do about it for now.

But there is a feature task that plans to use a cron-like syntax to start the speed-test. If you are in need of such a feature, you can follow the progress there: #889
