### ISSUE TITLE
[Bug] CPU Temperature not showing per Core

### ISSUE THREAD

**Issue by MatzHilven** [MauriceNino/dashdot#978]
### Description of the bug

When showing all of the CPU cores seperately the temperature per core isn't being shown (see images). Looking at the logs the temperatures are being retrieved fine, just not being displayed. It is working when not showing all cores seperately.

### Relevant log output

```shell
First measurement [CPU]: [

  { load: 1.550490236729872, temp: 55.504, core: 0 },

  { load: 1.6586475586015412, temp: 55.504, core: 1 },

  { load: 1.6710680269838032, temp: 55.504, core: 2 },

  { load: 1.6245208451849042, temp: 55.504, core: 3 }

]
```

### What browsers are you seeing the problem on?

Firefox

### Where is your instance running?

Raspberry Pi

### Additional context

![image](https://github.com/MauriceNino/dashdot/assets/48355802/82e6b266-9a3b-4ac0-b5e2-e693248af8d8)
![image](https://github.com/MauriceNino/dashdot/assets/48355802/5c00a9dd-265f-400a-a6ce-e8ee8fc71a05)

**Comment by MauriceNino** [comment]
The CPU temperature for every single core is often not available and even if it is, it would be hard to show it well on the small multicore graphs, because everything will look crammed, especially on CPUs with more than 4 cores.

Also, this is not a bug, this is completely on purpose, for design reasons. The same reason, why the percentages are also not shown on the multicore view.
